config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index', as: :home

  get '/cats' => "cats#index"

  get 'cats/new' => 'cats#new', as: :new_cat

  get '/cats/:id' => "cats#show", as: :cat

  post 'cats/' => 'cats#create'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :set_cat, only: [:show]


  def index
    @cats = Cat.all
    # @random = Cat.order('RAND()').limit(1)
    if params[:random]
      n = @cats.length
      rnd_idx = rand(0...n).limit(1)
      cat = @cats[rnd_idx]
      # render :show(cat)
      # redirect_to '/cats' + cat.id.to_s, cat_path(cat)
      redirect_to "/cats/#{cat.id}?random=true"
    end
  end

  def new
    @cat = Cat.new
  end

  def show
  end

  def create
    @cat = Cat.create(cat_params)

    if @cat.save
      redirect_to cat_path(@cat)
    else
      render :new
    end
  end

  private
    def set_cat
      @cat = Cat.find(params[:id])
      # use the :id to find one cat in the database
    end

    def cat_params
      params.require(:cat).permit(:name, :image_uri)
      # whitelist all of the vampire attributes so that your forms work!
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    # render '/welcome'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/index.html.erb
<div class="container text-center">

    <div class="row text-center cats">
  <% @cats.each do |cat| %>

        <div class="col-md-6 col-sm-12 hero-feature">
          <div class="thumbnail">
            <%= image_tag(cat.image_uri, height: "100", width: "200", class: "cat_pic") %><br>
            <div class="caption">
              <strong><%= cat.name %></strong>
              <p>Votes: <%= cat.votes %></p><br>
              <%= link_to "More Info", cat_path(cat) %><br>
           </div>
          </div>
        </div>

  <% end %>
    </div>

  <br>
</div>

app/views/cats/new.html.erb
<div class="container text-center">
  <br>
    <br>
      <br>

  <%= form_for @cat do |cat| %>
    <div>
      <%= cat.label :name %>
      <%= cat.text_field :name %>
    </div>
  <br>
    <div>
      <%= cat.label :image_uri %>
      <%= cat.text_field :image_uri %>
    </div>
  <br>
    <%= cat.submit "Create Profile" %>

  <% end %>

  <br><br>

  <%= link_to "Back", home_path %>
</div>

app/views/cats/show.html.erb
<div class="container text-center">

<h1><%= @cat.name %></h1>

  <br>
  <%= image_tag(@cat.image_uri, height: "300") %>
  <br> <br>
  <p>Votes: <%= @cat.votes %></p>
  <br>
   <br>

  <%= link_to "Back", cats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

</head>
<body>

<nav class="navbar navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <span class="navbar-brand">
        <%= link_to image_tag("catinder-logo.png", height: "28", class: "nav_logo"), home_path %>
        </span>
          <button type="button" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
      </div>
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav_links"><%= link_to "ALL CATS", cats_path %></li>
        <li class="nav_links"><%= link_to "RANDOM CAT", cats_path %></li>
        <li class="nav_links"><%= link_to "NEW CAT", new_cat_path%></li>
      </ul>
    </div>
  </nav>
  <hr>

  <%= image_tag("catinder-logo.png", height: "90", class: "logo image-responsive center-block") %>


<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container text-center">
  <br>
  <h1>Pets start here.</h1>
  <h3>Who is Meow, and who is Not-Meow? You decide!</h3>
  <br>
  <br>

  <h3 class="get_started"><%= link_to "get started >", '/cats?random=true' %></h3>
  <h2>Meet some of our many cats!</h2>
</div>